// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieBooking.API.Data;

#nullable disable

namespace MovieBooking.API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260721175220_CreateUsersTable")]
    partial class CreateUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MovieBooking.API.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAtUtc = new DateTime(2026, 7, 21, 17, 52, 18, 710, DateTimeKind.Utc).AddTicks(7035),
                            Email = "customer@example.com",
                            FullName = "Customer User",
                            IsActive = true,
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAtUtc = new DateTime(2026, 7, 21, 17, 52, 18, 710, DateTimeKind.Utc).AddTicks(8157),
                            Email = "manager@example.com",
                            FullName = "Manager User",
                            IsActive = true,
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAtUtc = new DateTime(2026, 7, 21, 17, 52, 18, 710, DateTimeKind.Utc).AddTicks(8161),
                            Email = "admin@example.com",
                            FullName = "Admin User",
                            IsActive = true,
                            Role = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
